layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: zhihao701
  # keybase: your_username
  linkedin: zhihao-shu-07b1361a2
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  youtube: HarryShu1997

topics:
  - name: Mobile AI
    image_url: https://www.webassetscdn.com/avira/prod-blog/wp-content/uploads/2019/03/ai-smartphone.jpg

  - name: Badminton
    image_url: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkmzi5m44O048ObOMqIE5yfVkyy6kzscoWwQ&usqp=CAU

  - name: Machine Learning
    image_url: https://miro.medium.com/v2/resize:fit:1024/1*k5LiTi5lt_ND02kaBT_SAA.jpeg

  - name: Travel
    image_url: https://res.cloudinary.com/enchanting/q_70,f_auto,w_800,h_500,c_fill,g_face/hj-web/2022/08/hawaii-oahu-island.png
